spring:
  application:
    name: S3FileManager

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/s3filemanager
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# === Yandex Object Storage ===
yandex:
  storage:
    accessKey: ${ACCESS_KEY}
    secretKey: ${SECRET_KEY}
    endpoint: https://storage.yandexcloud.net
    region: ru-central1
    bucketName: first-aws-bucket

# === Application Configuration ===
app:
  pageable:
    default-page-size: 10
    max-page-size: 20